#!/bin/bash

# TODO use variables for the case match and list
CHOICE=$(echo -e "screenshot\nselection\nmonitors\nrecord" | dmenu_fancy -p "Capture")

case $CHOICE in
  "screenshot")
    # TODO: maybe you can pass a screen index?
    flameshot screen --clipboard
    ;;
  "selection")
    flameshot gui
    ;;
  "monitors")
    flameshot full --clipboard
    ;;
  "record")
    peek
    ;;
  *)
    exit
    ;;
esac

