#!/bin/bash

alacritty -e nmtui connect &
pid="$!"

# Wait for the window to open and grab its window ID
winid=''
while : ; do
    winid="`wmctrl -lp | awk -vpid=$pid '$3==pid {print $1; exit}'`"
    [[ -z "${winid}" ]] || break
done

# Focus the window we found
wmctrl -ia "${winid}"

i3-msg floating enable > /dev/null;

#TODO: after resizing the ui is fucked up
i3-msg resize set 40 ppt 80 ppt

i3-msg move position center > /dev/null;

# Wait for the application to quit
wait "${pid}";
