#!/bin/bash

SCREENLAYOUTS=$(ls ~/.screenlayout/)
CHOICE=$(echo -e "manual\n$SCREENLAYOUTS" | dmenu_fancy -p "Choose screen layout?")

# NOTE: There shouldn't be a script named "manual" in ~/.screenlayout
if [ "$CHOICE" == "manual" ]; then
  arandr
else
  ~/.screenlayout/$CHOICE
fi

