#!/bin/bash

alacritty -e pulsemixer &
pid="$!"

# Wait for the window to open and grab its window ID
winid=''
while : ; do
    winid="`wmctrl -lp | awk -vpid=$pid '$3==pid {print $1; exit}'`"
    [[ -z "${winid}" ]] || break
done

# Focus the window we found
wmctrl -ia "${winid}"

i3-msg floating enable > /dev/null;

i3-msg resize set 80 ppt 60 ppt

i3-msg move position center > /dev/null;

# Wait for the application to quit
wait "${pid}";
